name: zig_build_and_test

on: push

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - name: Installing VulkanSDK
        run: sudo apt install libvulkan-dev
      - name: Building and Testing zig
        run: zig build test
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: Install VulkanSDK
        run: winget install -e --id KhronosGroup.VulkanSDK --accept-source-agreements --accept-package-agreements
      - name: Building and Testing zig
        run: zig build test
  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - name: Installing MoltenVK
        run: brew install molten-vk
      - name: Building and Testing zig
        run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig fmt --check .